# Generated by Django 4.2 on 2024-03-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
