# Generated by Django 4.2 on 2024-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_delete_enquiry_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='event',
            name='passed',
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=100),
        ),
    ]
